host = "theindependent.sg"
path = "-"
title = "h2.tdb-title-text"
thumb = "div.tdb-block-inner img.entry-thumb"
body = "div.td-post-content > div.tdb-block-inner > p"
skip_text = ["ALSO READ"]
skip_children = false